"""empty message

Revision ID: 0f816cc1891a
Revises: 530f7ef31c76
Create Date: 2026-06-30 12:03:32.833998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f816cc1891a'
down_revision: Union[str, Sequence[str], None] = '530f7ef31c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Webhooks', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('Webhooks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Webhooks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Webhooks', 'email')
    # ### end Alembic commands ###
