"""empty message

Revision ID: 200f3a6bb129
Revises: 6a0c284e6b51
Create Date: 2026-06-18 15:48:26.862363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200f3a6bb129'
down_revision: Union[str, Sequence[str], None] = '6a0c284e6b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentRequest', sa.Column('from_user_email', sa.String(), nullable=False))
    op.add_column('PaymentRequest', sa.Column('to_user_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PaymentRequest', 'to_user_email')
    op.drop_column('PaymentRequest', 'from_user_email')
    # ### end Alembic commands ###
