"""empty message

Revision ID: 2450960aa217
Revises: 65a6eecba168
Create Date: 2026-06-26 16:04:38.456137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2450960aa217'
down_revision: Union[str, Sequence[str], None] = '65a6eecba168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WebhooksLog', sa.Column('attemp_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WebhooksLog', 'attemp_number')
    # ### end Alembic commands ###
