"""empty message

Revision ID: 2888d6392e4f
Revises: 73fa0d81fc5a
Create Date: 2026-06-30 13:35:22.094359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2888d6392e4f'
down_revision: Union[str, Sequence[str], None] = '73fa0d81fc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Webhooks', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Webhooks', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
