"""empty message

Revision ID: 3063f2f13171
Revises: b3fa94cc4686
Create Date: 2026-05-31 17:29:54.436595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3063f2f13171'
down_revision: Union[str, Sequence[str], None] = 'b3fa94cc4686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('attempted_sender_email', sa.String(), nullable=True))
    op.add_column('Transaction', sa.Column('attempted_reciever_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'attempted_reciever_email')
    op.drop_column('Transaction', 'attempted_sender_email')
    # ### end Alembic commands ###
