"""empty message

Revision ID: 53da18dbd173
Revises: ff2e856976e5
Create Date: 2026-05-31 16:25:17.980586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53da18dbd173'
down_revision: Union[str, Sequence[str], None] = 'ff2e856976e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'sender_full_name')
    op.drop_column('Transaction', 'reciever_full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('reciever_full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Transaction', sa.Column('sender_full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
