"""empty message

Revision ID: 602f2bc721cf
Revises: bbc6c412a0d5
Create Date: 2026-06-19 15:23:54.944957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602f2bc721cf'
down_revision: Union[str, Sequence[str], None] = 'bbc6c412a0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentRequest', sa.Column('asker', sa.Integer(), nullable=True))
    op.add_column('Refund', sa.Column('asker', sa.Integer(), nullable=True))
    op.add_column('Transaction', sa.Column('asker', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'asker')
    op.drop_column('Refund', 'asker')
    op.drop_column('PaymentRequest', 'asker')
    # ### end Alembic commands ###
