"""empty message

Revision ID: 65a6eecba168
Revises: 
Create Date: 2026-06-21 20:41:53.369675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a6eecba168'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asker', sa.String(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('attempted_sender_id', sa.Integer(), nullable=True),
    sa.Column('reciever_id', sa.Integer(), nullable=True),
    sa.Column('attempted_reciever_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('attempted_sender_email', sa.String(), nullable=True),
    sa.Column('attempted_reciever_email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'frozen', name='status'), nullable=False),
    sa.Column('type', sa.Enum('transfer', 'deposit', 'refund', name='type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PaymentRequests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asker', sa.String(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_email', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_email', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'frozen', name='status'), nullable=False),
    sa.Column('type', sa.Enum('transfer', 'deposit', 'refund', name='type'), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asker', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'frozen', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WebhooksLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responce_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['Webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebhooksLog')
    op.drop_table('Refunds')
    op.drop_table('PaymentRequests')
    op.drop_table('Webhooks')
    op.drop_table('Transactions')
    op.drop_table('Users')
    # ### end Alembic commands ###
