"""empty message

Revision ID: 708d1ae89faa
Revises: 2450960aa217
Create Date: 2026-06-27 14:41:02.663729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708d1ae89faa'
down_revision: Union[str, Sequence[str], None] = '2450960aa217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'deleted_at')
    # ### end Alembic commands ###
