"""empty message

Revision ID: 73fa0d81fc5a
Revises: def308d97c35
Create Date: 2026-06-30 12:21:24.773105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fa0d81fc5a'
down_revision: Union[str, Sequence[str], None] = 'def308d97c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailLogDB', sa.Column('attempt_number', sa.Integer(), nullable=True))
    op.drop_column('EmailLogDB', 'attemp_number')
    op.add_column('WebhooksLog', sa.Column('attempt_number', sa.Integer(), nullable=True))
    op.drop_column('WebhooksLog', 'attemp_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WebhooksLog', sa.Column('attemp_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('WebhooksLog', 'attempt_number')
    op.add_column('EmailLogDB', sa.Column('attemp_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('EmailLogDB', 'attempt_number')
    # ### end Alembic commands ###
