"""empty message

Revision ID: 86f9525a9df8
Revises: f39e8d52a85e
Create Date: 2026-06-20 16:49:41.941076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f9525a9df8'
down_revision: Union[str, Sequence[str], None] = 'f39e8d52a85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentRequest', sa.Column('type', sa.Enum('transfer', 'deposit', 'refund', name='type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PaymentRequest', 'type')
    # ### end Alembic commands ###
