"""empty message

Revision ID: b3fa94cc4686
Revises: 53da18dbd173
Create Date: 2026-05-31 16:37:33.813363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fa94cc4686'
down_revision: Union[str, Sequence[str], None] = '53da18dbd173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'created_at')
    # ### end Alembic commands ###
