"""empty message

Revision ID: bac4bbc80bb1
Revises: 498c98ec58d3
Create Date: 2026-07-11 18:59:33.655211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac4bbc80bb1'
down_revision: Union[str, Sequence[str], None] = '498c98ec58d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Webhooks', sa.Column('failure_count', sa.Integer(), nullable=True))
    op.add_column('Webhooks', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('Webhooks', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Webhooks', 'deactivated_at')
    op.drop_column('Webhooks', 'is_active')
    op.drop_column('Webhooks', 'failure_count')
    # ### end Alembic commands ###
