"""empty message

Revision ID: bbc6c412a0d5
Revises: 200f3a6bb129
Create Date: 2026-06-19 13:50:05.496442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc6c412a0d5'
down_revision: Union[str, Sequence[str], None] = '200f3a6bb129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'refresh_token')
    op.drop_column('Users', 'access_token')
    # ### end Alembic commands ###
