"""empty message

Revision ID: bd091daf1590
Revises: d11c03ccae0d
Create Date: 2026-07-09 13:01:42.702259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd091daf1590'
down_revision: Union[str, Sequence[str], None] = 'd11c03ccae0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Webhooks', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Webhooks', 'email')
    # ### end Alembic commands ###
