"""empty message

Revision ID: d11c03ccae0d
Revises: d5f1eadd0dfb
Create Date: 2026-07-09 11:51:33.616794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11c03ccae0d'
down_revision: Union[str, Sequence[str], None] = 'd5f1eadd0dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'IdempotencyKeyDB', ['key', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'IdempotencyKeyDB', type_='unique')
    # ### end Alembic commands ###
