"""empty message

Revision ID: d5f1eadd0dfb
Revises: 8edf77c2381e
Create Date: 2026-07-09 11:39:32.054110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f1eadd0dfb'
down_revision: Union[str, Sequence[str], None] = '8edf77c2381e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IdempotencyKeyDB', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'IdempotencyKeyDB', 'Transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'IdempotencyKeyDB', type_='foreignkey')
    op.drop_column('IdempotencyKeyDB', 'transaction_id')
    # ### end Alembic commands ###
