"""empty message

Revision ID: d90285c6d02c
Revises: 
Create Date: 2026-06-17 11:38:02.247603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90285c6d02c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, time_zone=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PaymentRequest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'frozen', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('attempted_sender_id', sa.Integer(), nullable=True),
    sa.Column('reciever_id', sa.Integer(), nullable=True),
    sa.Column('attempted_reciever_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('attempted_sender_email', sa.String(), nullable=True),
    sa.Column('attempted_reciever_email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'frozen', name='status'), nullable=False),
    sa.Column('type', sa.Enum('transfer', 'deposit', 'refund', name='type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, time_zone=True),
    sa.ForeignKeyConstraint(['sender_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Refund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'frozen', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['Transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Refund')
    op.drop_table('Transaction')
    op.drop_table('PaymentRequest')
    op.drop_table('Users')
    # ### end Alembic commands ###
