"""empty message

Revision ID: def308d97c35
Revises: 0f816cc1891a
Create Date: 2026-06-30 12:19:35.445462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def308d97c35'
down_revision: Union[str, Sequence[str], None] = '0f816cc1891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmailLogDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responce_status', sa.String(), nullable=False),
    sa.Column('attemp_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['Webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EmailLogDB')
    # ### end Alembic commands ###
