"""empty message

Revision ID: f39e8d52a85e
Revises: a4b33fa320ca
Create Date: 2026-06-20 16:25:26.560717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39e8d52a85e'
down_revision: Union[str, Sequence[str], None] = 'a4b33fa320ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentRequest', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PaymentRequest', 'Transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PaymentRequest', type_='foreignkey')
    op.drop_column('PaymentRequest', 'transaction_id')
    # ### end Alembic commands ###
